config/routes.rb
Rails.application.routes.draw do
  resources :requests
  #resources :units
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  ##########
  #rutas para hacer que el cliente encuentre la informacion
  resources :requests, path: :client
  resources :units, path: :uf
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to request_url(@request), notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to request_url(@request), notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:user)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: %i[ show edit update destroy ]

  # GET /units or /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:value, :period)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valoruf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/_request.html.erb
<div id="<%= dom_id request %>">
  <p>
    <strong>User:</strong>
    <%= request.user %>
  </p>

</div>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Show this request", @request %> |
  <%= link_to "Back to requests", requests_path %>
</div>

app/views/requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Requests</h1>

<div id="requests">
  <% @requests.each do |request| %>
    <%= render request %>
    <p>
      <%= link_to "Show this request", request %>
    </p>
  <% end %>
</div>

<%= link_to "New request", new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Back to requests", requests_path %>
</div>

app/views/requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @request %>

<div>
  <%= link_to "Edit this request", edit_request_path(@request) %> |
  <%= link_to "Back to requests", requests_path %>

  <%= button_to "Destroy this request", @request, method: :delete %>
</div>

app/views/units/_form.html.erb
<%= form_with(model: unit) do |form| %>
  <% if unit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.label :period, style: "display: block" %>
    <%= form.date_field :period %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
  <p>
    <strong>Value:</strong>
    <%= unit.value %>
  </p>

  <p>
    <strong>Period:</strong>
    <%= unit.period %>
  </p>

</div>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Show this unit", @unit %> |
  <%= link_to "Back to units", units_path %>
</div>

app/views/units/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Units</h1>

<div id="units">
  <% @units.each do |unit| %>
    <%= render unit %>
    <p>
      <%= link_to "Show this unit", unit %>
    </p>
  <% end %>
</div>

<%= link_to "New unit", new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Back to units", units_path %>
</div>

app/views/units/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @unit %>

<div>
  <%= link_to "Edit this unit", edit_unit_path(@unit) %> |
  <%= link_to "Back to units", units_path %>

  <%= button_to "Destroy this unit", @unit, method: :delete %>
</div>